title: openSUSE Tumbleweed Review
description: |
  Summarized data about the changes and stability of Tumbleweed snapshots.

author: Jimmy Berry
email: jimmy@boombatower.com

url: https://boombatower.github.io/tumbleweed-review-site-dev
baseurl: "/tumbleweed-review-site-dev"

theme: minima
minima:
  date_format: "%Y-%m-%d"

show_excerpts: true
excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - CNAME
  - LICENSE
  - README.md
